export const phoneCodes = [
  {
    name: "United States",
    dial_code: "+1",
    key: "US",
  },
  { name: "Russia", dial_code: "+7", key: "RU" },
  { name: "Egypt", dial_code: "+20", key: "EG" },
  {
    name: "South Africa",
    dial_code: "+27",
    key: "ZA",
  },
  { name: "Greece", dial_code: "+30", key: "GR" },
  {
    name: "Netherlands",
    dial_code: "+31",
    key: "NL",
  },
  { name: "Belgium", dial_code: "+32", key: "BE" },
  { name: "France", dial_code: "+33", key: "FR" },
  { name: "Spain", dial_code: "+34", key: "ES" },
  { name: "Hungary", dial_code: "+36", key: "HU" },
  { name: "Italy", dial_code: "+39", key: "IT" },
  { name: "Romania", dial_code: "+40", key: "RO" },
  {
    name: "Switzerland",
    dial_code: "+41",
    key: "CH",
  },
  { name: "Austria", dial_code: "+43", key: "AT" },
  { name: "Guernsey", dial_code: "+44", key: "GG" },
  {
    name: "Isle of Man",
    dial_code: "+44",
    key: "IM",
  },
  { name: "Jersey", dial_code: "+44", key: "JE" },
  {
    name: "United Kingdom",
    dial_code: "+44",
    key: "GB",
  },
  { name: "Denmark", dial_code: "+45", key: "DK" },
  { name: "Sweden", dial_code: "+46", key: "SE" },
  { name: "Norway", dial_code: "+47", key: "NO" },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    key: "SJ",
  },
  { name: "Poland", dial_code: "+48", key: "PL" },
  { name: "Germany", dial_code: "+49", key: "DE" },
  { name: "Peru", dial_code: "+51", key: "PE" },
  { name: "Mexico", dial_code: "+52", key: "MX" },
  { name: "Cuba", dial_code: "+53", key: "CU" },
  {
    name: "Argentina",
    dial_code: "+54",
    key: "AR",
  },
  { name: "Brazil", dial_code: "+55", key: "BR" },
  { name: "Chile", dial_code: "+56", key: "CL" },
  { name: "Colombia", dial_code: "+57", key: "CO" },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    key: "VE",
  },
  { name: "Malaysia", dial_code: "+60", key: "MY" },
  {
    name: "Australia",
    dial_code: "+61",
    key: "AU",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    key: "CX",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    key: "CC",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    key: "ID",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    key: "PH",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    key: "NZ",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    key: "SG",
  },
  { name: "Thailand", dial_code: "+66", key: "TH" },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    key: "KZ",
  },
  { name: "Japan", dial_code: "+81", key: "JP" },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    key: "KR",
  },
  { name: "Vietnam", dial_code: "+84", key: "VN" },
  { name: "China", dial_code: "+86", key: "CN" },
  { name: "Turkey", dial_code: "+90", key: "TR" },
  { name: "India", dial_code: "+91", key: "IN" },
  { name: "Pakistan", dial_code: "+92", key: "PK" },
  {
    name: "Afghanistan",
    dial_code: "+93",
    key: "AF",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    key: "LK",
  },
  { name: "Myanmar", dial_code: "+95", key: "MM" },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    key: "IR",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    key: "SS",
  },
  { name: "Morocco", dial_code: "+212", key: "MA" },
  { name: "Algeria", dial_code: "+213", key: "DZ" },
  { name: "Tunisia", dial_code: "+216", key: "TN" },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    key: "LY",
  },
  { name: "Gambia", dial_code: "+220", key: "GM" },
  { name: "Senegal", dial_code: "+221", key: "SN" },
  {
    name: "Mauritania",
    dial_code: "+222",
    key: "MR",
  },
  { name: "Mali", dial_code: "+223", key: "ML" },
  { name: "Guinea", dial_code: "+224", key: "GN" },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    key: "CI",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    key: "BF",
  },
  { name: "Niger", dial_code: "+227", key: "NE" },
  { name: "Togo", dial_code: "+228", key: "TG" },
  { name: "Benin", dial_code: "+229", key: "BJ" },
  {
    name: "Mauritius",
    dial_code: "+230",
    key: "MU",
  },
  { name: "Liberia", dial_code: "+231", key: "LR" },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    key: "SL",
  },
  { name: "Ghana", dial_code: "+233", key: "GH" },
  { name: "Nigeria", dial_code: "+234", key: "NG" },
  { name: "Chad", dial_code: "+235", key: "TD" },
  {
    name: "Central African Republic",
    dial_code: "+236",
    key: "CF",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    key: "CM",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    key: "CV",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    key: "ST",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    key: "GQ",
  },
  { name: "Gabon", dial_code: "+241", key: "GA" },
  { name: "Congo", dial_code: "+242", key: "CG" },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    key: "CD",
  },
  { name: "Angola", dial_code: "+244", key: "AO" },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    key: "GW",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    key: "IO",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    key: "SC",
  },
  { name: "Sudan", dial_code: "+249", key: "SD" },
  { name: "Rwanda", dial_code: "+250", key: "RW" },
  {
    name: "Ethiopia",
    dial_code: "+251",
    key: "ET",
  },
  { name: "Somalia", dial_code: "+252", key: "SO" },
  {
    name: "Djibouti",
    dial_code: "+253",
    key: "DJ",
  },
  { name: "Kenya", dial_code: "+254", key: "KE" },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    key: "TZ",
  },
  { name: "Uganda", dial_code: "+256", key: "UG" },
  { name: "Burundi", dial_code: "+257", key: "BI" },
  {
    name: "Mozambique",
    dial_code: "+258",
    key: "MZ",
  },
  { name: "Zambia", dial_code: "+260", key: "ZM" },
  {
    name: "Madagascar",
    dial_code: "+261",
    key: "MG",
  },
  { name: "Mayotte", dial_code: "+262", key: "YT" },
  { name: "Reunion", dial_code: "+262", key: "RE" },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    key: "ZW",
  },
  { name: "Namibia", dial_code: "+264", key: "NA" },
  { name: "Malawi", dial_code: "+265", key: "MW" },
  { name: "Lesotho", dial_code: "+266", key: "LS" },
  {
    name: "Botswana",
    dial_code: "+267",
    key: "BW",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    key: "SZ",
  },
  { name: "Comoros", dial_code: "+269", key: "KM" },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    key: "SH",
  },
  { name: "Eritrea", dial_code: "+291", key: "ER" },
  { name: "Aruba", dial_code: "+297", key: "AW" },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    key: "FO",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    key: "GL",
  },
  {
    name: "Cayman Islands",
    dial_code: "+345",
    key: "KY",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    key: "GI",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    key: "PT",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    key: "LU",
  },
  { name: "Ireland", dial_code: "+353", key: "IE" },
  { name: "Iceland", dial_code: "+354", key: "IS" },
  { name: "Albania", dial_code: "+355", key: "AL" },
  { name: "Malta", dial_code: "+356", key: "MT" },
  { name: "Cyprus", dial_code: "+357", key: "CY" },
  {
    name: "Aland Islands",
    dial_code: "+358",
    key: "AX",
  },
  { name: "Finland", dial_code: "+358", key: "FI" },
  {
    name: "Bulgaria",
    dial_code: "+359",
    key: "BG",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    key: "LT",
  },
  { name: "Latvia", dial_code: "+371", key: "LV" },
  { name: "Estonia", dial_code: "+372", key: "EE" },
  { name: "Moldova", dial_code: "+373", key: "MD" },
  { name: "Armenia", dial_code: "+374", key: "AM" },
  { name: "Belarus", dial_code: "+375", key: "BY" },
  { name: "Andorra", dial_code: "+376", key: "AD" },
  { name: "Monaco", dial_code: "+377", key: "MC" },
  {
    name: "San Marino",
    dial_code: "+378",
    key: "SM",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    key: "VA",
  },
  { name: "Ukraine", dial_code: "+380", key: "UA" },
  { name: "Serbia", dial_code: "+381", key: "RS" },
  {
    name: "Montenegro",
    dial_code: "+382",
    key: "ME",
  },
  { name: "Croatia", dial_code: "+385", key: "HR" },
  {
    name: "Slovenia",
    dial_code: "+386",
    key: "SI",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    key: "BA",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    key: "MK",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    key: "CZ",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    key: "SK",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    key: "LI",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    key: "FK",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    key: "GS",
  },
  { name: "Belize", dial_code: "+501", key: "BZ" },
  {
    name: "Guatemala",
    dial_code: "+502",
    key: "GT",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    key: "SV",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    key: "HN",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    key: "NI",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    key: "CR",
  },
  { name: "Panama", dial_code: "+507", key: "PA" },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    key: "PM",
  },
  { name: "Haiti", dial_code: "+509", key: "HT" },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    key: "GP",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    key: "BL",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    key: "MF",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    key: "BO",
  },
  { name: "Ecuador", dial_code: "+593", key: "EC" },
  {
    name: "French Guiana",
    dial_code: "+594",
    key: "GF",
  },
  { name: "Guyana", dial_code: "+595", key: "GY" },
  {
    name: "Paraguay",
    dial_code: "+595",
    key: "PY",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    key: "MQ",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    key: "SR",
  },
  { name: "Uruguay", dial_code: "+598", key: "UY" },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    key: "AN",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    key: "TL",
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    key: "AQ",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    key: "NF",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    key: "BN",
  },
  { name: "Nauru", dial_code: "+674", key: "NR" },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    key: "PG",
  },
  { name: "Tonga", dial_code: "+676", key: "TO" },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    key: "SB",
  },
  { name: "Vanuatu", dial_code: "+678", key: "VU" },
  { name: "Fiji", dial_code: "+679", key: "FJ" },
  { name: "Palau", dial_code: "+680", key: "PW" },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    key: "WF",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    key: "CK",
  },
  { name: "Niue", dial_code: "+683", key: "NU" },
  { name: "Samoa", dial_code: "+685", key: "WS" },
  {
    name: "Kiribati",
    dial_code: "+686",
    key: "KI",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    key: "NC",
  },
  { name: "Tuvalu", dial_code: "+688", key: "TV" },
  {
    name: "French Polynesia",
    dial_code: "+689",
    key: "PF",
  },
  { name: "Tokelau", dial_code: "+690", key: "TK" },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    key: "FM",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    key: "MH",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    key: "KP",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    key: "HK",
  },
  { name: "Macao", dial_code: "+853", key: "MO" },
  {
    name: "Cambodia",
    dial_code: "+855",
    key: "KH",
  },
  { name: "Laos", dial_code: "+856", key: "LA" },
  {
    name: "Pitcairn",
    dial_code: "+872",
    key: "PN",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    key: "BD",
  },
  { name: "Taiwan", dial_code: "+886", key: "TW" },
  {
    name: "Maldives",
    dial_code: "+960",
    key: "MV",
  },
  { name: "Lebanon", dial_code: "+961", key: "LB" },
  { name: "Jordan", dial_code: "+962", key: "JO" },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    key: "SY",
  },
  { name: "Iraq", dial_code: "+964", key: "IQ" },
  { name: "Kuwait", dial_code: "+965", key: "KW" },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    key: "SA",
  },
  { name: "Yemen", dial_code: "+967", key: "YE" },
  { name: "Oman", dial_code: "+968", key: "OM" },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    key: "PS",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    key: "AE",
  },
  { name: "Israel", dial_code: "+972", key: "IL" },
  { name: "Bahrain", dial_code: "+973", key: "BH" },
  { name: "Qatar", dial_code: "+974", key: "QA" },
  { name: "Bhutan", dial_code: "+975", key: "BT" },
  {
    name: "Mongolia",
    dial_code: "+976",
    key: "MN",
  },
  { name: "Nepal", dial_code: "+977", key: "NP" },
  {
    name: "Tajikistan",
    dial_code: "+992",
    key: "TJ",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    key: "TM",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    key: "AZ",
  },
  { name: "Georgia", dial_code: "+995", key: "GE" },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    key: "KG",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    key: "UZ",
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    key: "BS",
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    key: "BB",
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    key: "AI",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    key: "AG",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    key: "VG",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    key: "VI",
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    key: "BM",
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    key: "GD",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    key: "TC",
  },
  {
    name: "Montserrat",
    dial_code: "+1664",
    key: "MS",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    key: "MP",
  },
  { name: "Guam", dial_code: "+1671", key: "GU" },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    key: "AS",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    key: "LC",
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    key: "DM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    key: "VC",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    key: "DO",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    key: "TT",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    key: "KN",
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    key: "JM",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    key: "PR",
  },
  {
    name: "Select",
    dial_code: "Select",
    key: "select",
  },
];
